[build]
  command = "npm run build"
  publish = ".netlify"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@aztec/bb.js",
    "@noir-lang/noir_js",
    "@noir-lang/noirc_abi",
    "@noir-lang/acvm_js"
  ]
  
  included_files = [
    # WASM files from node_modules
    "node_modules/@aztec/bb.js/dest/node/barretenberg_wasm/**",
    "node_modules/@noir-lang/noirc_abi/nodejs/**",
    "node_modules/@noir-lang/acvm_js/nodejs/**"
  ]
